name: my_gpu_env
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python=3.13
  - numpy
  - pandas
  - cuda-toolkit=12.0
  - pip
  - pip:
    - -r requirements.txt # If you have additional pip dependencies13
